# Generated by Django 2.1.15 on 2020-06-09 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automate_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleReprocess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('project', models.CharField(max_length=64)),
                ('remote_path', models.CharField(max_length=256)),
                ('batch_size', models.IntegerField()),
                ('task_size', models.IntegerField()),
                ('nproc', models.IntegerField()),
                ('beamx', models.FloatField()),
                ('beamy', models.FloatField()),
                ('action', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='automate_app.Action')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
