# Generated by Django 2.1.15 on 2020-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanzus_index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplereprocess',
            name='batch_size',
        ),
        migrations.RemoveField(
            model_name='samplereprocess',
            name='task_size',
        ),
        migrations.AddField(
            model_name='samplereprocess',
            name='aps_data_root',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='samplereprocess',
            name='options_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='samplereprocess',
            name='run_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
