# Generated by Django 2.1.7 on 2019-05-28 21:14
# Updated by Django 2.2.1 on 2019-06-03 22:35


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('concierge_id', models.IntegerField()),
                ('index', models.CharField(max_length=32)),
                ('minid', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cache', models.TextField(default='{}')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StageBag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=32)),
                ('concierge_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cache', models.TextField(default='{}')),
                ('bag', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='concierge_app.Bag')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
