# Generated by Django 2.2.5 on 2020-01-14 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concierge_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=128)),
                ('project', models.CharField(max_length=128, default='')),
                ('query', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=128, default='')),
                ('subjects_data', models.TextField(default='[]')),
                ('filters_data', models.TextField(default='[]')),
                ('metadata_data', models.TextField(default='{}')),
                ('cached_search_data', models.TextField(default='{}')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MDFCollectionSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=256, default='')),
                ('source_id', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256, default='')),
                ('cache', models.TextField(default='{}')),
                ('search_collection', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='concierge_app.SearchCollection')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bag',
            name='search_collection',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='concierge_app.SearchCollection'
            ),
        ),
    ]
