# Generated by Django 2.1.15 on 2020-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge_app', '0002_mdf_publish_and_search_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_id', models.UUIDField()),
                ('index', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cache', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifest_transfer_id', models.UUIDField()),
                ('index', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cache', models.TextField(default='{}')),
            ],
        ),
        migrations.RemoveField(
            model_name='bag',
            name='search_collection',
        ),
        migrations.RemoveField(
            model_name='bag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stagebag',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='stagebag',
            name='user',
        ),
    ]
