# Generated by Django 2.1.15 on 2020-09-17 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concierge_app', '0003_concierge_app_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='StageBag',
        ),
        migrations.AddField(
            model_name='manifesttransfer',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concierge_app.Manifest'),
        ),
        migrations.AddField(
            model_name='manifesttransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manifest',
            name='search_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='concierge_app.SearchCollection'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
