# Generated by Django 2.1.15 on 2020-02-27 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('payload_data', models.TextField()),
                ('cache_data', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('flow_id', models.UUIDField()),
                ('group', models.UUIDField(null=True)),
                ('title', models.CharField(max_length=256)),
                ('scope', models.CharField(max_length=256)),
                ('definition_filename', models.CharField(max_length=512, null=True)),
                ('definition_checksum', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='flow',
            name='authorized_consumers',
            field=models.ManyToManyField(to='automate_app.FlowConsumer'),
        ),
        migrations.AddField(
            model_name='action',
            name='flow',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='automate_app.Flow'
            ),
        ),
        migrations.AddField(
            model_name='action',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
