# Generated by Django 3.1.7 on 2021-03-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('automate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flow',
            name='authorized_consumers',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='definition_filename',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='group',
        ),
        migrations.AddField(
            model_name='action',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FlowInstanceAuthorizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.UUIDField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=128)),
                ('access_token', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=128)),
                ('expires_at_seconds', models.FloatField()),
                ('delegations', models.ManyToManyField(related_name='flow_delegations', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automate_app.flow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
