# Generated by Django 3.1.13 on 2021-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automate_app', '0002_gladier_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='parameter_data',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
